SELECT HISTORY_ID, CAST((DATEDIFF(END_DATE, START_DATE)+1) * (DAILY_FEE * DISCOUNT_RATE) AS signed integer) AS FEE
FROM (
         SELECT h.HISTORY_ID, h.END_DATE, h.START_DATE, c.DAILY_FEE, 1 AS DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
                  JOIN CAR_RENTAL_COMPANY_CAR as c
                       ON h.CAR_ID = c.CAR_ID
         WHERE CAR_TYPE = '트럭' AND DATEDIFF(h.END_DATE, h.START_DATE) < 7

         UNION
         SELECT h.HISTORY_ID, h.END_DATE, h.START_DATE, c.DAILY_FEE, (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭'))*0.01 AS DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
                  JOIN CAR_RENTAL_COMPANY_CAR as c
                       ON h.CAR_ID = c.CAR_ID
         WHERE CAR_TYPE = '트럭' AND DATEDIFF(h.END_DATE, h.START_DATE) BETWEEN 7 AND 29

         UNION
         SELECT h.HISTORY_ID, h.END_DATE, h.START_DATE, c.DAILY_FEE, (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭'))*0.01 AS DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
                  JOIN CAR_RENTAL_COMPANY_CAR as c
                       ON h.CAR_ID = c.CAR_ID
         WHERE CAR_TYPE = '트럭' AND DATEDIFF(h.END_DATE, h.START_DATE) BETWEEN 30 AND 89

         UNION
         SELECT h.HISTORY_ID, h.END_DATE, h.START_DATE, c.DAILY_FEE, (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭'))*0.01 AS DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
                  JOIN CAR_RENTAL_COMPANY_CAR as c
                       ON h.CAR_ID = c.CAR_ID
         WHERE CAR_TYPE = '트럭' AND DATEDIFF(h.END_DATE, h.START_DATE) >= 90) AS target
ORDER BY FEE DESC, HISTORY_ID DESC;