SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (
         SELECT USER_ID, NICKNAME, STATUS, SUM(PRICE) AS TOTAL_SALES
         FROM (USED_GOODS_BOARD AS B
             JOIN USED_GOODS_USER AS U
               ON U.USER_ID = B.WRITER_ID)
         GROUP BY U.USER_ID, U.NICKNAME, STATUS
         HAVING B.STATUS="DONE"
     ) AS T
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES